add homework 4
08-11-2022-FE/Bohdan_Dobrov_4 pull request #1
Opened 2022-11-20 17:53 UTC by BohdanDobrov

@savkaoleg будь ласка перевір мое домашнє завдання

2022-11-21 19:48 UTC, savkaoleg requested changes

2022-11-21 19:48 UTC, savkaoleg commented on index.html
> +                    <img src="images/safari.svg" alt="opera" target="_blank" width="35" height="35">
Для чого для зображення писати target="_blank"?

2022-11-21 19:48 UTC, savkaoleg commented on index.html
> +            <p>ЕЕлемент &lt;article&gt; визначає незалежний, автономний вміст.</p>
Одрук

2022-11-21 19:48 UTC, savkaoleg commented on index.html
> +                ЗСтаття повинна мати сенс самостійно, і вона повинна мати можливість
Одрук

2022-11-21 19:48 UTC, savkaoleg commented on index.html
> +            >
атрибут title oбов'язковий

2022-11-22 12:07 UTC, BohdanDobrov commented
@savkaoleg виправив помилки

2022-11-26 17:31 UTC, savkaoleg approved these changes
Молодець!

2022-11-26 17:31 UTC, merged